version: 0.0.{build}

platform:
    - x86

skip_commits:
  message: /\[ci skip\]/

matrix:
    fast_finish: true

build_script:
    - git submodule update --init --recursive
    - SET PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
    # Build default configuration
    - make dist
    # Build configuration with SPIFFS_USE_MAGIC_LENGTH=0 (legacy version)
    - make clean
    - make dist BUILD_CONFIG_NAME="-no_magic_length" CFLAGS="-DSPIFFS_USE_MAGIC_LENGTH=0 -DSPIFFS_ALIGNED_OBJECT_INDEX_TABLES=1"

artifacts:
  - path: '*.zip'

deploy:
    release: $(PRODUCT_VERSION)
    provider: GitHub
    auth_token:
        secure: 'exejPglIPIQteWFNOUBqPhMxVjA84wktH0xF4rI/IVcsD9UG0Wc/M/xzIl/sie9h'
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
        appveyor_repo_tag: true
